name: Spring Boot Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

            cd backend
            git pull
            mvn clean package
            pkill java || true
            nohup java -jar target/*.jar > app.log 2>&1 &
